package section cleanup, added nbconvert+pandoc, setup zsh as default shell

diff --git a/.devcontainer/amd64/Dockerfile b/.devcontainer/amd64/Dockerfile
--- a/.devcontainer/amd64/Dockerfile
+++ b/.devcontainer/amd64/Dockerfile
@@ -55,6 +55,7 @@ RUN apt-get update && \
     zip unzip bzip2 \
     libjpeg-dev libpng-dev libpq-dev \
     imagemagick gnuplot gnuplot-x11 libssl-dev libzmq3-dev graphviz \
+    pandoc libxml2-dev libxslt-dev \
     # opencv
     libopencv-dev \
     # py3
@@ -64,7 +65,6 @@ RUN apt-get update && \
     python3-venv \
     python3-wheel \
     python3-setuptools && \
-    #python3-opencv \ # 4.6.0
     # Cleanup
     apt-get autoremove -fy && \
     apt-get clean && \
@@ -91,29 +91,75 @@ RUN pip config --user set global.disable-pip-version-check true && \
 
 # Install Python Packages using uv
 RUN uv pip install \
-    ipykernel docutils jupyter notebook jupyterhub \
-    # Code Formatters
-    jupyterlab-code-formatter watermark pyyaml pylint ruff black isort \
-    # LSP
-    jupyterlab-lsp python-lsp-server python-lsp-black python-lsp-ruff python-lsp-isort \
+    # Jupyter
+    ipykernel jupyter notebook jupyterhub jupyter-book \
+    # Jupyterlab Extensions
+    jupyterlab-code-formatter \
+    jupyterlab-lsp \
     jupyterlab-spellchecker \
     jupyterlab-execute-time \
-    tensorflow \
-    matplotlib seaborn plotly graphviz \
-    keras \
+    # Jupyter Tools
+    nbconvert papermill[black] \
+    # Python
+    pyyaml pylint ruff black[jupyter] isort \
+    python-lsp-server python-lsp-black python-lsp-ruff python-lsp-isort \
+    docutils watermark bottleneck requests_cache \
+    # Learning
+    tensorflow keras \
+    # Graphics and Visualization
+    matplotlib seaborn plotly bokeh graphviz imutils \
+    # CPU-only OpenCV
     opencv-python-headless \
-    imutils \
-    numpy pandas pandas-datareader bottleneck h5py \
-    scipy scikit-learn \
-    duckdb \
-    sqlalchemy \
+    # Data Analysis
+    numpy pandas pandas-datareader \
+    # ML
+    scipy scikit-learn statsmodels \
+    # DB
+    duckdb sqlalchemy \
+    # Automation
     pyautogui \
-    requests_cache \
+    # Finance
     yfinance alpha_vantage nasdaq-data-link finnhub-python financetoolkit financedatabase \
-    statsmodels
+    # Data
+    h5py
 
 # Install ipykernel
 RUN /opt/venv/bin/python -m ipykernel install --user --name="jupyter_devbox" --display-name="jupyter_devbox_python3_venv"
 
+# +----------------------------------------------------------------------+
+# | Setup zsh, ohmyzsh, powerline fonts.                                 |
+# | Setup zsh plugins: autosuggestions, autocompletions, history search. |
+# +----------------------------------------------------------------------+
+
+ENV TERM=xterm-256color \
+    ZSH_THEME=agnoster
+
+# Setup zsh for the root user
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN echo "ZSH" && \
+    apt-get update && apt-get install --no-install-recommends --assume-yes \
+    zsh fontconfig fonts-powerline && \
+    # Install Oh My Zsh
+    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh && \
+    # Add Zsh plugins
+    git clone --depth=1 --no-tags https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
+    git clone --depth=1 --no-tags https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions && \
+    git clone --depth=1 --no-tags https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search && \
+    # Update .zshrc
+    sed -i \
+      -e 's/^plugins=(git.*)/plugins=(git zsh-completions zsh-autosuggestions zsh-history-substring-search)/' \
+      -e 's/^ZSH_THEME="[^"]*"/ZSH_THEME="robbyrussell"/' \
+      -e 's/^# *DISABLE_UPDATE_PROMPT="true"/DISABLE_UPDATE_PROMPT="true"/' \
+      -e 's/^# *DISABLE_AUTO_UPDATE="true"/DISABLE_AUTO_UPDATE="true"/' \
+    /root/.zshrc && \
+	# Cleanup
+	apt-get autoremove -y && \
+    apt-get clean autoclean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+# Set the default shell to zsh after it is installed
+ENV SHELL=/bin/zsh
+
 # Re-enable dialog mode for apt-get
 ENV DEBIAN_FRONTEND=dialog
+
diff --git a/.devcontainer/arm64v8/Dockerfile b/.devcontainer/arm64v8/Dockerfile
--- a/.devcontainer/arm64v8/Dockerfile
+++ b/.devcontainer/arm64v8/Dockerfile
@@ -50,31 +50,14 @@ RUN groupadd --gid $USER_GID $USERNAME && \
 
 RUN apt-get update && \
     apt-get -y install --no-install-recommends \
-        git zsh curl wget nano openssh-client ca-certificates tzdata locales \
-        gcc g++ build-essential cmake ninja-build \
-        zip unzip bzip2
-
-# Set locale and timezone
-RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
-ENV LANG=en_US.utf8 TZ=Etc/UTC
-
-# Install Rust
-#RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs > /tmp/rustup.sh \
-#  && sh /tmp/rustup.sh -y --default-toolchain stable
-#ENV HOME=/root
-#ENV PATH=$HOME/.cargo/bin:$PATH
-#RUN rustup --version && cargo --version && rustc --version
-#RUN rustup update
-
-RUN apt-get -y install --no-install-recommends \
+    git zsh curl wget nano openssh-client ca-certificates tzdata locales \
+    gcc g++ build-essential cmake ninja-build \
+    zip unzip bzip2 \
     libjpeg-dev libpng-dev libpq-dev \
     imagemagick gnuplot gnuplot-x11 libssl-dev libzmq3-dev graphviz \
-    re2c libffi-dev libffi8 gfortran libxsimd-dev libhdf5-serial-dev \
-    libxml2-dev libxslt-dev \
-    # OPENCV
+    pandoc libxml2-dev libxslt-dev \
+    # opencv
     libopencv-dev \
-    # BLAS and LAPACK, OPENBLAS and BLIS
-    libblas-dev liblapack-dev libopenblas-dev libblis-dev \
     # py3
     python3 \
     python3-dev \
@@ -87,6 +70,10 @@ RUN apt-get -y install --no-install-recommends \
     apt-get clean && \
     apt-get autoclean -y && \
     rm -rf /var/lib/apt/lists/*
+
+# Set locale and timezone
+RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
+ENV LANG=en_US.utf8 TZ=Etc/UTC
 
 # Use a virtual environment for Python (to avoid PEP668 "externally managed environment" error).
 ENV VIRTUAL_ENV=/opt/venv
@@ -104,29 +91,74 @@ RUN pip config --user set global.disable-pip-version-check true && \
 
 # Install Python Packages using uv
 RUN uv pip install \
-    ipykernel docutils jupyter notebook jupyterhub \
-    # Code Formatters
-    jupyterlab-code-formatter watermark pyyaml pylint ruff black isort \
-    # LSP
-    jupyterlab-lsp python-lsp-server python-lsp-black python-lsp-ruff python-lsp-isort \
+    # Jupyter
+    ipykernel jupyter notebook jupyterhub jupyter-book \
+    # Jupyterlab Extensions
+    jupyterlab-code-formatter \
+    jupyterlab-lsp \
     jupyterlab-spellchecker \
     jupyterlab-execute-time \
-    tensorflow \
-    matplotlib seaborn plotly graphviz \
-    keras \
+    # Jupyter Tools
+    nbconvert papermill[black] \
+    # Python
+    pyyaml pylint ruff black[jupyter] isort \
+    python-lsp-server python-lsp-black python-lsp-ruff python-lsp-isort \
+    docutils watermark bottleneck requests_cache \
+    # Learning
+    tensorflow keras \
+    # Graphics and Visualization
+    matplotlib seaborn plotly bokeh graphviz imutils \
+    # CPU-only OpenCV
     opencv-python-headless \
-    imutils \
-    numpy pandas pandas-datareader bottleneck h5py \
-    scipy scikit-learn \
-    duckdb \
-    sqlalchemy \
+    # Data Analysis
+    numpy pandas pandas-datareader \
+    # ML
+    scipy scikit-learn topt statsmodels \
+    # DB
+    duckdb sqlalchemy \
+    # Automation
     pyautogui \
-    requests_cache \
+    # Finance
     yfinance alpha_vantage nasdaq-data-link finnhub-python financetoolkit financedatabase \
-    statsmodels
+    # Data
+    h5py
 
 # Install ipykernel
 RUN /opt/venv/bin/python -m ipykernel install --user --name="jupyter_devbox" --display-name="jupyter_devbox_python3_venv"
+
+# +----------------------------------------------------------------------+
+# | Setup zsh, ohmyzsh, powerline fonts.                                 |
+# | Setup zsh plugins: autosuggestions, autocompletions, history search. |
+# +----------------------------------------------------------------------+
+
+ENV TERM=xterm-256color \
+    ZSH_THEME=agnoster
+
+# Setup zsh for the root user
+SHELL ["/bin/bash", "-o", "pipefail", "-c"]
+RUN echo "ZSH" && \
+    apt-get update && apt-get install --no-install-recommends --assume-yes \
+    zsh fontconfig fonts-powerline && \
+    # Install Oh My Zsh
+    curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh | sh && \
+    # Add Zsh plugins
+    git clone --depth=1 --no-tags https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions && \
+    git clone --depth=1 --no-tags https://github.com/zsh-users/zsh-completions ${ZSH_CUSTOM:=~/.oh-my-zsh/custom}/plugins/zsh-completions && \
+    git clone --depth=1 --no-tags https://github.com/zsh-users/zsh-history-substring-search ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-history-substring-search && \
+    # Update .zshrc
+    sed -i \
+      -e 's/^plugins=(git.*)/plugins=(git zsh-completions zsh-autosuggestions zsh-history-substring-search)/' \
+      -e 's/^ZSH_THEME="[^"]*"/ZSH_THEME="robbyrussell"/' \
+      -e 's/^# *DISABLE_UPDATE_PROMPT="true"/DISABLE_UPDATE_PROMPT="true"/' \
+      -e 's/^# *DISABLE_AUTO_UPDATE="true"/DISABLE_AUTO_UPDATE="true"/' \
+    /root/.zshrc && \
+	# Cleanup
+	apt-get autoremove -y && \
+    apt-get clean autoclean && \
+    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
+
+# Set the default shell to zsh after it is installed
+ENV SHELL=/bin/zsh
 
 # Re-enable dialog mode for apt-get
 ENV DEBIAN_FRONTEND=dialog
